Implemented: Local packages and add repositories db.

diff --git a/tools/find-downloaded-content b/tools/find-downloaded-content
--- a/tools/find-downloaded-content
+++ b/tools/find-downloaded-content
@@ -6,5 +6,19 @@ fi
 TYPE=$1
 NAME=$2
 
-echo $PAK_C_MAK_PATH/downloads/$TYPE/$NAME
+if [[ $PAK_C_MAK_LOCAL_PACKAGES =~ (^|[[:space:]])$NAME($|[[:space:]]) ]]; then
+	DOWNLOADABLE_NAME=$(realpath "$PAK_C_MAK_PATH/../$NAME")
+	
+	if [ ! -d "$DOWNLOADABLE_NAME" ]; then
+		echo '$PAK_C_MAK_LOCAL_PACKAGES is set to' $NAME >&2 ;
+		echo "But $DOWNLOADABLE_NAME not found" >&2 ;
+		exit 1;
+	fi
+
+	echo $DOWNLOADABLE_NAME
+else
+	echo $PAK_C_MAK_PATH/pak_c_mak_tmp/downloads/$TYPE/$NAME
+fi
+
+
 
